name: Build Docker Container after Django Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test_django:
    uses: DevKor-github/DevKor-teamB-back/.github/workflows/kua-test.yml@main
  env:
      working-directory: ./KUA
      DEBUG: "0"
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{secrets.DB_HOST}}  # localhost since postgres service runs on the same host
      DB_PORT: 5432
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      
  container_builder:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build container image
        run: |
          docker build \
          -t euizzang8001/kua-backend:${GITHUB_SHA::7} \
          -t euizzang8001/kua-backend:latest \
          .
        working-directory: ${{ env.working-directory }}
